algoritmo "ex2"
// Função :
// Autor :
// Data : 24/10/2022
// Seção de Declarações 
var
n1,n2:real
nome:literal
inicio
// Seção de Comandos
procedimento mostra (a,b:real;c:literal)
inicio
escreval ("O valor de n1 é: ", a)
escreval ("O valor de n2 é: ", b)
escreval ("O nome é; ", c)
fimprocedimento

escreva ("Informe o valor de n1: ")
leia (n1)

escreva ("informe o valor de n2: ")
leia (n2)

escreva ("Informe o nome: ")
leia (nome)

mostra(n1,n2,nome)

fimalgoritmo
