algoritmo "semnome"
//Faça um algoritmo para somar os numeros pares <1000 e ao final imprimir o resultado.
//Faça com o comando enquanto e com comando MOD.
// se (contador mod 2 = 0) entao
var
numero,soma,contador:inteiro
inicio

enquanto contador <> 999 faca
contador <- contador + 1
se (contador mod 2 = 0) entao
soma <- contador + soma

fimse
fimenquanto

escreval (" A SOMA É",soma)
fimalgoritmo
