algoritmo "semnome"
//Criar um algoritmo que leia 10 numeros pelo tecdaldo e exiba os numetos na ordem
//normal da que os numeros foram digitados
var
contador:inteiro
numeros:vetor [1..10] de inteiro
inicio

para contador de 1 ate 10 faca
   escreva ("Informe o numeros: ")
   leia (numeros[contador])
fimpara

para contador de 1 ate 10 faca
   escreval ("O Número é: ", numeros[contador])

fimpara
fimalgoritmo
