algoritmo "semnome"
//Faça um algoritmo que leia 10 numeros reais em vetor e depois mostreb os numeros
//localizados nas posições impares
var
contador:inteiro
numeros:vetor [1..10] de real
inicio

para contador de 1 ate 10 faca
   escreva ("Informe o numeros: ")
   leia (numeros[contador])
fimpara

para contador de 1 ate 10 passo 2 faca
   escreval ("O Número é: ", numeros[contador])

fimpara
fimalgoritmo
