//Faça um algoritmo que receba o valor do salario minimo e o valor
//do salario que um trabalhador recebe. Calcular e mostrar quantos salarios
//minimos esse trabalhador recebe

algoritmo "salariominimo"

var
smin, sint, resultado:real

inicio
escreval ("insira aqui o salario minimo")
leia (smin)

escreval ("insira aqui o seu salario")
leia (sint)

resultado <- (sint/smin)
escreval ("Voce recebe", resultado)




fimalgoritmo









